# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-23 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IPapp', '0005_auto_20170422_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='rating',
            field=models.CharField(max_length=4),
        ),
    ]
