# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-23 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IPapp', '0002_auto_20170422_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='addressC',
            new_name='customerAddress',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='addressV',
            new_name='vendorAddress',
        ),
    ]
