# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-23 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IPapp', '0004_auto_20170422_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='auto_now_add=True')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('passwordC', models.CharField(max_length=40)),
                ('nameC', models.CharField(max_length=40)),
                ('customerAddress', models.CharField(max_length=60)),
                ('emailC', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('iType', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=140)),
                ('menu_fmenuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPapp.MenuCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('rate', models.IntegerField()),
                ('customer_freview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=140)),
                ('review_freviewflag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPapp.Review')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='auto_now_add=True')),
                ('total', models.FloatField()),
                ('tax', models.FloatField()),
                ('customer_fsale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPapp.Customer')),
                ('item_fsale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPapp.MenuItem')),
                ('menu_fsale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPapp.MenuCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorAddress', models.CharField(max_length=60)),
                ('emailV', models.CharField(max_length=40)),
                ('passwordV', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('rating', models.FloatField()),
                ('nameV', models.CharField(max_length=40)),
                ('approved', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='vendor_fsale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPapp.Vendor'),
        ),
        migrations.AddField(
            model_name='review',
            name='vendor_freview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPapp.Vendor'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='vendor_fmenucategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPapp.Vendor'),
        ),
        migrations.AddField(
            model_name='advertising',
            name='vendor_fadvertising',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IPapp.Vendor'),
        ),
    ]
